name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: minh
          POSTGRES_DB: book_api
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: minh
      DB_NAME: book_api
      DB_PORT: 5432
      JWT_SECRET: nqmgaming

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install dependencies
        run: go mod download

      - name: Tidy modules
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Build
        run: go build -v ./...

      - name: Build Docker image
        run: docker build -t go-api .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag go-api:latest nqmgaming/go-api:latest
          docker push nqmgaming/go-api:latest